spring.application.name=budgeting
spring.ai.openai.api-key=${OPENAI_API_KEY:}

spring.docker.compose.skip.in-tests=false

spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:transaction}
spring.datasource.username=${POSTGRES_USER:app}
spring.datasource.password=${POSTGRES_PASSWORD:app}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.ai.openai.chat.options.model=gpt-4o-mini

spring.ai.model.audio.transcription=openai
spring.ai.openai.audio.transcription.options.model=whisper-1
spring.ai.openai.audio.transcription.options.language=es
spring.ai.openai.audio.transcription.options.temperature=0
spring.ai.openai.audio.transcription.options.response-format=text
spring.ai.openai.audio.transcription.options.prompt=El audio esta en español. \
  El audio tiene descripciónes de gastos financieros. \
  Las frases contienen valores en pesos argentinos. \
  Las frases generalmente contienen: \
    - un valor en pesos argentinos \
    - una acción (gasté, pagué, etc) \
    - un local o establecimiento (farmacia, bar) \
  La respuesta debe ser un texto con el formato: \
    - valor en pesos argentinos (70.000 pesos, 50.000 pesos, 5.000 pesos) \
    - acción \
    - local o establecimiento

spring.ai.model.audio.speech=openai
spring.ai.openai.audio.speech.options.model=gpt-4o-mini-tts
spring.ai.openai.audio.speech.options.voice=nova
spring.ai.openai.audio.speech.options.speed=1.2
spring.ai.openai.audio.speech.options.response-format=mp3
