CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL DEFAULT 'USER'
);

ALTER TABLE transaction_entity
    ADD COLUMN owner_id BIGINT;

ALTER TABLE transaction_entity
    ADD CONSTRAINT fk_transaction_entity_owner
        FOREIGN KEY (owner_id) REFERENCES app_user(id);
