CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_password_reset_token_user
        FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_password_reset_token_user_unused
    ON password_reset_token (user_id)
    WHERE used_at IS NULL;
